framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true
    #trusted_hosts: ~
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    session:
        storage_id: 'session.storage.native'
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: 'PHPSESSID'
        cookie_lifetime: 0

    assets:
        base_urls: '%env(BASE_URLS)%'

    #esi: ~
    #fragments: ~
    php_errors:
        log: true


