security:
    encoders:
            App\Entity\User:
                algorithm: bcrypt

    role_hierarchy:
            ROLE_VALIDATOR: [ROLE_USER]
            ROLE_ADMIN: [ROLE_VALIDATOR]

    providers:
        main:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            provider: main
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: home
                always_use_default_target_path: true
            logout:
                path: logout
                target: /accueil
            remember_me:
                secret: '%env(SECRET)%'
                lifetime: 259200 # 3 days
                path: /
                httponly: true

    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/observations/en-attente-de-validation, roles: ROLE_VALIDATOR}
            - { path: ^/observations/nouvelle-observation, roles: ROLE_USER }
            - { path: ^/historique-des-observations, roles: ROLE_USER }
            - { path: ^/mon-profil, roles: ROLE_USER }
            - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/accueil, roles: IS_AUTHENTICATED_ANONYMOUSLY }




