twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        search: '@App\Services\Search'
    form_themes:
        - 'bootstrap_3_layout.html.twig'



