home:
    path: /
    defaults:
         _controller: App\Controller\IndexController::home

register:
    path: /connexion/inscription
    defaults:
        _controller: App\Controller\IndexController::register

askNewPswd:
    path: /mot-de-passe-oublier
    defaults:
        _controller: App\Controller\IndexController:resetPswdMail

resetPswd:
    path: /mot-de-passe-oublier/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::resetPswdForm

validation:
    path: /validation/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::activate

addReport:
     path: /observations/nouvelle-observation
     defaults:
         _controller: App\Controller\IndexController::AddReport

aboutUs:
    path: /nao-et-ses-partenaires
    defaults:
        _controller:
cgu:
    path: /cgu
    defaults:
        _controller:


controllers:
   resource: ../src/Controller/
   type: annotation
