home:
    path: /
    defaults:
         _controller: App\Controller\IndexController::home

register:
    path: /connexion/inscription
    defaults:
        _controller: App\Controller\IndexController::register

aboutUs:
    path: /nao-et-ses-partenaires
    defaults:
        _controller:

cgu:
    path: /cgu
    defaults:
        _controller:

validation:
    path: /validation/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::activate

controllers:
   resource: ../src/Controller/
   type: annotation
