landing:
    path: /
    defaults:
        _controller: App\Action\LandingAction

home:
    path: /accueil
    defaults:
        _controller: App\Action\HomeAction

login:
    path: /connexion
    defaults:
        _controller: App\Controller\IndexController::login

login_check:
    path: /login

logout:
    path: /logout

register:
    path: /connexion/inscription
    defaults:
        _controller: App\Controller\IndexController::register

askNewPswd:
    path: /mot-de-passe-oublier
    defaults:
        _controller: App\Controller\IndexController::resetPswdMail

resetPswd:
    path: /mot-de-passe-oublier/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::resetPswdForm
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

validation:
    path: /validation/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::activate
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

report:
    path: /observations/{state}
    defaults:
        _controller: App\Action\BrowseReportAction
    requirements:
        state: valide||en-attente-de-validation

addReport:
     path: /observations/nouvelle-observation
     defaults:
         _controller: App\Controller\IndexController::addReport

search:
    path: /resultat-de-la-recherche
    defaults:
        _controller: App\Action\SearchAction

historic:
    path: /historique-des-observations/{species}/{birdId}
    defaults:
        _controller: App\Controller\IndexController::birdHistory
    requirements:
        birdId: \d+


notification:
     path: /notification
     defaults:
         _controller: App\Controller\IndexController::userNotification

profile:
    path: /mon-profil/{name}-{surname}/{id}
    defaults:
        _controller: App\Controller\IndexController::profile
    requirements:
        name: ([a-zA-z]{3,})
        surname: ([a-zA-z]{3,})
        id: \d+
admin:
    path: /admin
    defaults:
        _controller: App\Controller\IndexController::administration

userList:
    path: /admin/liste-des-membres
    defaults:
        _controller: App\Controller\IndexController::userList

userManagement:
    path: /admin/{action}/{id}
    defaults:
        _controller: App\Controller\IndexController::accountManagement
        id: null
    requirements:
        action: deactivate||ban||privilege||validate||deny||delete
        id: \d+

exportCsv:
    path: /admin/export-report
    defaults:
        _controller: App\Controller\IndexController::export


accountValidation:
    path: /admin/demande-accès-naturaliste
    defaults:
        _controller: App\Controller\IndexController::accountLvl2Request

unactivated:
        path: /admin/comptes-innactifs
        defaults:
           _controller: App\Controller\IndexController::unactivatedAccount
bird:
    path: /admin/liste-des-espèces
    defaults:
        _controller:  App\Controller\IndexController::listReportedBird

statistics:
    path: /admin/statistiques
    defaults:
        _controller: App\Controller\IndexController::statistics

aboutUs:
    path: /nao-et-ses-partenaires
    defaults:
        _controller:  App\Controller\IndexController::aboutUs

terms:
    path: /conditions-generales-d-utilisation
    defaults:
        _controller: App\Controller\IndexController::terms

star:
   path: /star/{reportId}
   defaults:
      _controller: App\Controller\IndexController::starReport
   requirements:
       reportId: \d+

validateReport:
   path: /validation/{reportId}
   defaults:
       _controller: App\Controller\IndexController::validateReport
   requirements:
       reportId: \d+

controllers:
   resource: ../src/Controller/
   type: annotation



