landing:
    path: /
    defaults:
        _controller: App\Action\LandingAction

home:
    path: /accueil
    defaults:
        _controller: App\Action\HomeAction

login:
    path: /connexion
    defaults:
        _controller: App\Action\Security\LoginAction

login_check:
    path: /login

logout:
    path: /logout

register:
    path: /connexion/inscription
    defaults:
        _controller: App\Action\Security\RegisterAction

askNewPswd:
    path: /mot-de-passe-oublier
    defaults:
        _controller: App\Action\ResetPswdMailAction

resetPswd:
    path: /mot-de-passe-oublier/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Action\ResetPswdFormAction
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

validation:
    path: /validation/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Action\ActivateAction
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

report:
    path: /observations/{state}
    defaults:
        _controller: App\Action\BrowseReportAction
    requirements:
        state: valide||en-attente-de-validation

addReport:
     path: /observations/nouvelle-observation
     defaults:
         _controller: App\Action\AddReportAction

historic:
    path: /historique-des-observations/{species}/{birdId}
    defaults:
        _controller: App\Action\BirdHistoryAction
    requirements:
        birdId: \d+


notification:
     path: /notification
     defaults:
         _controller: App\Action\NotificationAction

profile:
    path: /mon-profil/{name}-{surname}/{id}
    defaults:
        _controller: App\Action\ProfileAction
    requirements:
        name: ([a-zA-z]{3,})
        surname: ([a-zA-z]{3,})
        id: \d+

admin:
    path: /admin
    defaults:
        _controller: App\Action\Admin\AdminHomeAction

userList:
    path: /admin/liste-des-membres
    defaults:
        _controller: App\Action\Admin\UserListAction

userManagement:
    path: /admin/{action}/{id}
    defaults:
        _controller: App\Action\Admin\AccountManagementAction
        id: null
    requirements:
        action: deactivate||ban||privilege||validate||deny||delete
        id: \d+

exportCsv:
    path: /admin/export-report
    defaults:
        _controller: App\Action\Admin\ExportCsvAction

accountValidation:
    path: /admin/demande-acces-naturaliste
    defaults:
        _controller: App\Action\Admin\Level2RequestAction

unactivated:
        path: /admin/comptes-inactifs
        defaults:
           _controller: App\Action\Admin\UnactivatedListAction
bird:
    path: /admin/liste-des-especes
    defaults:
        _controller:  App\Action\Admin\ReportedBirdAction

aboutUs:
    path: /nao-et-ses-partenaires
    defaults:
        _controller:  App\Action\AboutUsAction

terms:
    path: /conditions-generales-d-utilisation
    defaults:
        _controller: App\Action\TermsAction

star:
   path: /star/{reportId}
   defaults:
      _controller: App\Action\StarReportAction
   requirements:
       reportId: \d+

validateReport:
   path: /validation/{reportId}
   defaults:
       _controller: App\Action\ValidateReportAction
   requirements:
       reportId: \d+





