home:
    path: /
    defaults:
        _controller: App\Controller\IndexController::home

login:
    path: /connexion
    defaults:
        _controller: App\Controller\IndexController::login

login_check:
    path: /login

logout:
    path: /logout

register:
    path: /connexion/inscription
    defaults:
        _controller: App\Controller\IndexController::register

askNewPswd:
    path: /mot-de-passe-oublier
    defaults:
        _controller: App\Controller\IndexController::resetPswdMail

resetPswd:
    path: /mot-de-passe-oublier/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::resetPswdForm
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

validation:
    path: /validation/{expireOn}/{email}/{token}
    defaults:
        _controller: App\Controller\IndexController::activate
    requirements:
        expireOn: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])
        email: ^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$
        token: ([^']{40,})

report:
    path: /observations
    defaults:
        _controller:

addReport:
     path: /observations/nouvelle-observation
     defaults:
         _controller: App\Controller\IndexController::AddReport

unvalidated:
     path: /observations/en-attente-de-validation
     defaults:
         _controller: App\Controller\IndexController

notification:
    path: /notifications
    defaults:
        _controller: App\Controller\IndexController

notification:
     path: /notification
     defaults:
         _controller: App\Controller\IndexController::AddReport


profile:
    path: /mon-profil/{name}-{surname}
    defaults:
        _controller: App\Controller\IndexController::profile
    requirements:
        name: ([a-zA-z]{3,})
        surname: ([a-zA-z]{3,})

admin:
    path: /admin
    defaults:
       _controller: App\Controller\IndexController::Administration

aboutUs:
    path: /nao-et-ses-partenaires
    defaults:
        _controller:

cgu:
    path: /cgu
    defaults:
        _controller:

star:
   path: /star/{reportId}
   defaults:
      _controller: App\Controller\IndexController::starReport
   requirements:
       reportId: \d+


controllers:
   resource: ../src/Controller/
   type: annotation


